# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
name: "Update Check Run"
description: "Update the status of a commit check using the GH CLI. See https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run"
inputs:
  # Composite actions do not support typed parameters. Everything is treated as a string
  # See: https://github.com/actions/runner/issues/2238
  gh-token:
    description: "The GitHub token for use with the CLI"
    required: true
  repository:
    description: "The GitHub repository"
    required: true
    default: "apache/kafka"
  commit_sha:
    description: "The SHA of the commit we are updating"
    required: true
  url:
    description: "The URL of the status check"
    required: false
    default: ""
  description:
    description: "The text to display next to the check"
    default: ""
    required: false
  title:
    description: "The title of the status check"
    required: true
  status:
    description: "The status of the check. Can be one of: queued, in_progress, completed, waiting, requested, pending"
    required: true
  conclusion:
    description: "Required if status is 'completed'. Can be one of: action_required, cancelled, failure, neutral, success, skipped, stale, timed_out"
    required: false

runs:
  using: "composite"
  steps:
    - if: inputs.conclusion == ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      run: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ inputs.repository }}/check-runs \
        -f "head_sha=${{ inputs.commit_sha }}" \
        -f "status=${{ inputs.status }}" \
        -f "details_url=${{ inputs.url }}" \
        -f "output[title]=${{ inputs.title }}" \
        -f "output[summary]=${{ inputs.description }}" \
        -f "name=${{ inputs.title }}"
    - if: inputs.conclusion != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      run: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ inputs.repository }}/check-runs \
        -f "head_sha=${{ inputs.commit_sha }}" \
        -f "status=${{ inputs.status }}" \
        -f "conclusion=${{ inputs.conclusion }}" \
        -f "details_url=${{ inputs.url }}" \
        -f "output[title]=${{ inputs.title }}" \
        -f "output[summary]=${{ inputs.description }}" \
        -f "name=${{ inputs.title }}"
