name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '*/10 * * * *'

permissions:
  pull-requests: read

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          debug-only: true
          days-before-stale: 30
          days-before-close: -1
