name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run'
        required: true
        default: true
        type: boolean
      operationsPerRun:
        description: 'Max GitHub API operations'
        required: true
        default: 30
        type: number

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          debug-only: ${{ inputs.dryRun }}
          operations-per-run: ${{ inputs.operationsPerRun }}
          days-before-stale: 30
          days-before-close: -1
          stale-issue-label: 'stale'

